local util = dofile("util.lua")

function VasGolem()
	util.select("minecraft:iron_block")
	turtle.place()
	turtle.up()
	turtle.place()
	turtle.turnLeft()
	turtle.forward()
	turtle.turnRight()
	turtle.place()
	turtle.turnRight()
	turtle.forward()
	turtle.forward()
	turtle.turnLeft()
	turtle.place()
	turtle.turnLeft()
	turtle.forward()
	turtle.turnRight()
	turtle.up()
	util.select("minecraft:pumpkin")
	turtle.place()
	print("Reszkessetek zombik, csontvázak, pókok! Itt van az új csodafegyver! Ha-ha-ha-ha!")
end

VasGolem()
